seperate dnsproxy from activeprotectsensor
firewalla/firewalla pull request #3661
Opened 2021-06-22 11:01 UTC by cli8910

2021-06-22 17:27 UTC, MelvinTo commented on sensor/ActiveProtectSensor.js
> +const alreadyAppliedFlag = "default_c_init_done_dns_proxy";
need another flag to handle the migration, not replace the current one

2021-06-23 08:05 UTC, jasonlyc requested changes

2021-06-23 08:05 UTC, jasonlyc commented on control/CategoryUpdater.js
> +  isUserCustomized(category) {
Consider using existing isCustomizedCategory in CategoryUpdater.js

2021-06-24 11:48 UTC, jasonlyc approved these changes

2021-06-24 12:03 UTC, merged