Flow Compression for faster access
firewalla/firewalla pull request #3977
Opened 2021-09-14 03:34 UTC by wzjjack

2021-09-14 03:37 UTC, wzjjack commented
https://github.com/firewalla/firecommit/issues/879

2021-09-14 06:07 UTC, drahnieR requested changes

2021-09-15 07:26 UTC, drahnieR approved these changes

2021-09-26 04:55 UTC, drahnieR requested changes

2021-09-26 04:55 UTC, drahnieR commented on sensor/FlowCompressionSensor.js
> +      } else if (await rclient.ttlAsync(key) < await rclient.ttlAsync(oldestKey)) {
If comparing begin and end in the key name is sufficient, don't invoke 2 redis calls here

2021-09-26 04:55 UTC, drahnieR commented on sensor/FlowCompressionSensor.js
> +      await rclient.delAsync(oldestKey)
deleting the oldest one might not be sufficient here, maybe accumulating memory size from the latest one, and delete all earlier keys once mem cap is reached.

2021-09-26 07:15 UTC, drahnieR requested changes

2021-09-26 07:18 UTC, drahnieR approved these changes

2021-09-26 07:51 UTC, MelvinTo approved these changes

2021-09-26 07:51 UTC, merged