add wan block flows to compression
firewalla/firewalla pull request #4083
Opened 2021-11-04 17:20 UTC by wzjjack

2021-11-05 09:23 UTC, drahnieR requested changes

2021-11-05 09:23 UTC, drahnieR commented on sensor/FlowCompressionSensor.js
> +          await this.appendAndSave(ts, await this.compress(allFlows), 'wanBlock')
All data is kept in array and then sent to zlib, creates a big memory consumption. Using pipe should be a better approach. Same problem in build().

2021-11-05 10:16 UTC, drahnieR approved these changes

2021-11-08 02:52 UTC, MelvinTo approved these changes

2021-11-08 02:53 UTC, merged